language: python
python:
 - "2.6"
 - "3.6"
stages:
 - displayHelp
 - startService
jobs:
 include:
  - stage: displayHelp
    script: ./snow-grafana-proxy.py --help
  - stage: startService
    script: ./snow-grafana-proxy.py
