language: python
stages:
 - displayHelp
 - startService
jobs:
 include:
  - stage: displayHelp
    script: ./snow-grafana-proxy.py --help
    python:
     - "3.6"
  - stage: startService
    script: ./snow-grafana-proxy.py -c ./etc/snow-grafana-proxy.conf
    python:
     - "3.6"
