language: python
stages:
 - test
 - displayHelp
 - startService
script: ./snow-grafana-proxy.py -c ./etc/snow-grafana-proxy.conf
python:
 - "2.7"
 - "3.5"
 - "3.6"

jobs:
 include:
  - stage: displayHelp
    script: ./snow-grafana-proxy.py --help
    python:
     - "3.6"
  - stage: startService
    script: ./snow-grafana-proxy.py -c ./etc/snow-grafana-proxy.conf
    python:
     - "2.7"
     - "3.5"
     - "3.6"
